stages:
  - release

goreleaser:
  stage: release
  image: goreleaser/goreleaser:latest
  only:
    - tags
  script:
    - goreleaser release --clean
  release:
    tag_name: $CI_COMMIT_TAG
    description: 'Release $CI_COMMIT_TAG'
